server:
  port: 8002
spring:
  application:
    name: EurekaServer
eureka:
  instance:
    hostname: server2
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/,http://server3:8003/eureka/
    register-with-eureka: false
    fetch-registry: false