server:
  port: 9001
spring:
  application:
    name: producer
  zipkin:
    base-url: http://localhost:8004
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/
#  instance:
#    hostname: produce1