server:
  port: 8321
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WhoopsMqq/application.git #配置git仓库地址
          #search-paths:    #git仓库地址下的相对地址，可以配置多个，用,分割。
          username: whoops_mqq@163.com
          password: mqq981025940
    bus:
      enabled: true
      trace:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh