server:
  port: 7001
spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://server1:8001/eureka/
feign:
  hystrix:
    enabled: true